// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pg} from '../models';

export function AvailableVersions():Promise<Array<string>>;

export function ConnectionString(arg1:string):Promise<string>;

export function CreateInstance(arg1:string,arg2:string,arg3:number):Promise<void>;

export function DeleteInstance(arg1:string):Promise<void>;

export function DeleteVersion(arg1:string):Promise<void>;

export function InstalledVersions():Promise<Array<pg.InstalledVersion>>;

export function Log(arg1:string,arg2:number):Promise<string>;

export function OpenDataDir(arg1:string):Promise<void>;

export function Start(arg1:string):Promise<void>;

export function Status():Promise<Array<pg.InstanceStatus>>;

export function Stop(arg1:string):Promise<void>;
