// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AvailableVersions() {
  return window['go']['main']['App']['AvailableVersions']();
}

export function ConnectionString(arg1) {
  return window['go']['main']['App']['ConnectionString'](arg1);
}

export function CreateInstance(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateInstance'](arg1, arg2, arg3);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function OpenDataDir(arg1) {
  return window['go']['main']['App']['OpenDataDir'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}
